/**
 * @fileoverview gRPC-Web generated client stub for chatlab.grpc
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.12
// source: chat.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as chat_pb from './chat_pb';


export class ChatGrpcClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSendMessage = new grpcWeb.MethodDescriptor(
    '/chatlab.grpc.ChatGrpc/SendMessage',
    grpcWeb.MethodType.UNARY,
    chat_pb.MessageSend,
    chat_pb.Message,
    (request: chat_pb.MessageSend) => {
      return request.serializeBinary();
    },
    chat_pb.Message.deserializeBinary
  );

  sendMessage(
    request: chat_pb.MessageSend,
    metadata: grpcWeb.Metadata | null): Promise<chat_pb.Message>;

  sendMessage(
    request: chat_pb.MessageSend,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: chat_pb.Message) => void): grpcWeb.ClientReadableStream<chat_pb.Message>;

  sendMessage(
    request: chat_pb.MessageSend,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: chat_pb.Message) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/chatlab.grpc.ChatGrpc/SendMessage',
        request,
        metadata || {},
        this.methodDescriptorSendMessage,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/chatlab.grpc.ChatGrpc/SendMessage',
    request,
    metadata || {},
    this.methodDescriptorSendMessage);
  }

  methodDescriptorStreamChat = new grpcWeb.MethodDescriptor(
    '/chatlab.grpc.ChatGrpc/StreamChat',
    grpcWeb.MethodType.SERVER_STREAMING,
    chat_pb.StreamRequest,
    chat_pb.Message,
    (request: chat_pb.StreamRequest) => {
      return request.serializeBinary();
    },
    chat_pb.Message.deserializeBinary
  );

  streamChat(
    request: chat_pb.StreamRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<chat_pb.Message> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/chatlab.grpc.ChatGrpc/StreamChat',
      request,
      metadata || {},
      this.methodDescriptorStreamChat);
  }

}

